ALTER TYPE "ModerationSubjectType" ADD VALUE IF NOT EXISTS 'CAMPUS';
ALTER TYPE "ModerationSubjectType" ADD VALUE IF NOT EXISTS 'REPORT';

ALTER TYPE "ModerationActionType" ADD VALUE IF NOT EXISTS 'ARCHIVE';
ALTER TYPE "ModerationActionType" ADD VALUE IF NOT EXISTS 'TRIAGE';
ALTER TYPE "ModerationActionType" ADD VALUE IF NOT EXISTS 'DISMISS';
ALTER TYPE "ModerationActionType" ADD VALUE IF NOT EXISTS 'RESOLVE';
